.github/workflows/CI.yml
download_data_for_tests.sh

CI will now fail if the resulting FITS files for point-like or full-enclosure if not exactly the same as for test cases.
Tested in https://github.com/VERITAS-Observatory/V2DL3/runs/5420886207?check_suite_focus=true

Minor updates to smoothen CI workflow

---

.github/workflows/CI.yml
notebooks/eventdisplay-testing/compareFitsFiles.py
notebooks/gammapy_util.py
pyV2DL3/eventdisplay/EventDisplayDataSource.py
pyV2DL3/eventdisplay/fillEVENTS.py
pyV2DL3/eventdisplay/util.py
pyV2DL3/fillEVENTS.py
pyV2DL3/gammapy_util.py
pyV2DL3/script/v2dl3_qsub.py
pyV2DL3/vegas/VegasDataSource.py
pyV2DL3/vegas/fillEVENTS_not_safe.py
pyV2DL3/vegas/irfloader.py
pyV2DL3/vegas/util.py
setup.py

Enabled  static code checking with flake8 in CI:
- CI will fail now when flake8 is not executed successfully (before: used `--exit-zero`)
- adapted several files to follow standards (mostly sequence of imports and docstrings)

Minor updates to allow static code tests to give reasonable results.

---

pyV2DL3/eventdisplay/EventDisplayDataSource.py
pyV2DL3/eventdisplay/fillEVENTS.py
pyV2DL3/eventdisplay/fillRESPONSE.py

wobble offset value was not stored for logging in EventDisplayDataSource.py [here](https://github.com/VERITAS-Observatory/V2DL3/blob/1181214225f03c2d701ad30b0ef54a700e360e90/pyV2DL3/eventdisplay/EventDisplayDataSource.py#L49). This PR reads wobble offset from anasum runSummary and writes out for logging.

remove unused parameter 'offset' 

---

pyV2DL3/eventdisplay/fillRESPONSE.py

This is a minor modification to use consistently the IRF tree fEffAreaH2F and not in this single place fEffArea.
This should have no impact on any results, the only difference should be a small performance improvement (as fEffAreaH2F has a factor of 20 less entries than fEffArea).
@sona-patel - would still be good to test this for an epoch where you see larger differences between eventdisplay and gammapy analysis.

Use consistently fEffAreaH2F as IRF tree

---

CITATION.cff

Adding a citation file, to allow users to cite this repository correctly. We follow the CITATION.cff convention, as suggested by github (see [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)).
Author list is in reverse order, meaning first contributors are listed first.
I have a hard time with affiliations, so any help is appreciated. Let me know if anything is missing.
@amandajw-isu - not sure how I should handle the Iowa contributions. I am following now strictly the github list of contributors, but I think this would be incomplete?

Adding a citation file

---

pyV2DL3/fillEVENTS.py
pyV2DL3/fillRESPONSE.py
pyV2DL3/genHDUList.py
pyV2DL3/script/v2dl3_for_vegas.py
pyV2DL3/vegas/VegasDataSource.py
pyV2DL3/vegas/fillEVENTS_not_safe.py

This patch utilizes the previously implemented "EventClass" object in order to select events to separate event lists and FITS files.
New flags have been tested and output has been reproduced with no differences to main using fitsdiff.
Very little VEGAS-specific review here, so I've added a question about how we utilize VEGAS root data in the previous patch.
- `fillEVENTS_not_safe.py` accesses additional `selectedEventsTree` attributes `.fMSW` and `.fMSL` in the manner specified by VEGAS docs
- From previous commit 6c6e3f2: 
- `EventClass.py` reads EA via VARootIO to get the cuts info ("pfCutsFileText" in the root file)
- `fCutsFileText` is passed (as a string) to `getCuts()` in `util.py` to search for substrings matching the desired cut param names.
- This seems to me to be a naive …

v2dl3-vegas: Event Selection Patch

---

pyV2DL3/generateObsHduIndex.py

Generating index files has been bugged for VEGAS by pull request #150. After testing a couple solutions, I propose this fix to handle keys added to the `names` List which are not present at runtime.

Generate Index Files Bugfix

---

.github/workflows/v2dl3-eventdisplay-packaging.yml
pyV2DL3/script/compareFitsFiles.py
utils/v2dl3-eventdisplay-docker/Dockerfile
utils/v2dl3-eventdisplay-docker/README.md

Add functionality to generate a Docker image for each release and each merge to main for the V2DL3-Eventdisplay. Docker images are pushed to https://github.com/VERITAS-Observatory/V2DL3/pkgs/container/v2dl3 with the correct metadata and naming.
Usage is described in https://github.com/VERITAS-Observatory/V2DL3/tree/eventdisplay_docker/utils/v2dl3-eventdisplay-docker
Packages are published here: https://github.com/VERITAS-Observatory/V2DL3/pkgs/container/v2dl3
Package area is at this point private, but I've asked our VERITAS github admins to make it public.

V2DL3 for Eventdisplay Docker Image Production

---

pyV2DL3/vegas/EffectiveAreaFile.py

The offset array read from the IRF requires >1 items when creating the background map. In the case of a single offset table (like wobble of 0.5 degree), add both 0 and 10.0 deg offsets when none are found inside the IRF, since two numbers are necessary. The table repeats for each entry.

Expand offset array when none present.

---

utils/v2dl3-eventdisplay-docker/Dockerfile
utils/v2dl3-eventdisplay-docker/README.md

Use of micromamba base image simplifies docker installation for Eventdisplay significantly.

Simplified docker installation for Eventdisplay

---

pyV2DL3/eventdisplay/IrfExtractor.py
pyV2DL3/eventdisplay/IrfInterpolator.py
pyV2DL3/eventdisplay/fillEVENTS.py
pyV2DL3/eventdisplay/fillRESPONSE.py
pyV2DL3/eventdisplay/util.py

Improve the robustness and error search for processing a large number of files:
- consistently use `logging.error` before raising exceptions
- replace logging.exceptions by logging.errors (as full trace is not needed)
- handle numpy warnings

Robustness of Eventdisplay preprocessing

---

pyV2DL3/eventdisplay/IrfInterpolator.py
pyV2DL3/script/generate_index_file.py

This allows to read directories with a large number of fits files (beyond the limit of ls, which will give an error message /bin/sh: /bin/ls: Argument list too long)

Replace call to ls by glob.glob

---

.pre-commit-config.yaml
environment-eventdisplay.yml

This adds a pre-commit configuration file to run the following steps for each commit:
- flake8 linter
- sorting of imports
- remove trailing spaces
Run `pre-commit install` before using it first in the V2DL3 directory.

Add pre-commit tools

---

README.md
pyV2DL3/eventdisplay/IrfInterpolator.py
pyV2DL3/eventdisplay/fillEVENTS.py
pyV2DL3/eventdisplay/fillRESPONSE.py
pyV2DL3/script/v2dl3_for_Eventdisplay.py
pyV2DL3/tests/test_fillRESPONSE.py
utils/download_Eventdisplay_test_data.sh

We have observations outside of the parameter space of our instrument response functions. These are typically very low-elevation runs (IRFs start at 30 deg elevation only; e.g., the Galactic center culminates below) or very dark/bright NSB runs.
IRF interpolation allows to extend slightly beyond the boundaries using the `---fuzzy_boundary` parameter. 
This pull request introduce IRF axes dependent `-fuzzy_boundary` parameters, with the motivation that the IRF dependence with zenith angle is much stronger than the one with pedvar (NSB). So there is good motivation to have a somewhat more relaxed fuzzy boundary for the NSB axes.
Instead of using `--fuzzy_boundary 0.05`, give now the tolerance per IRF axis:  `--fuzzy_boundary pedvar 0.10 --fuzzy_boundary zenith 0.05` (only those two axes are …

Introduce axis dependent fuzzy boundaries (Eventdisplay converter)

---

.github/workflows/v2dl3-codeChecking.yml
.github/workflows/v2dl3-eventdisplay.yml
environment-eventdisplay.yml
pyV2DL3/constant.py
pyV2DL3/generateObsHduIndex.py
utils/compare_fits_dirs.sh
utils/download_Eventdisplay_test_data.sh
utils/prepare_Eventdisplay_CI.sh

Add integration tests for
- with / without DB files
- with / without event filter
Requires new CI files.

Add additional Eventdisplay integration tests

---

pyV2DL3/eventdisplay/fillRESPONSE.py
pyV2DL3/fillEVENTS.py
utils/download_Eventdisplay_test_data.sh
utils/prepare_Eventdisplay_CI.sh

Fixes:
- add units to Xoff/Xoff entries in event list
- consistent writing in lower case in FITS comments

Add units to Xoff/Yoff; fixes in comments and writing

---

README.md
environment-vegas.yml
pyV2DL3/script/v2dl3_for_vegas.py
pyV2DL3/vegas/irfloader.py
setup.py

Remove the usage of root_numpy, which is outdated and no longer supported. Complying with #86 and #88. 
Fix the loading of multiple run-groups in the runlist. 
Minor edit to README including instructions for mamba installation alternative (#175).

Remove root numpy  and process multiple run groups

---

pyV2DL3/eventdisplay/fillEVENTS.py

This PR allows to run V2DL3 on Eventdisplay anasum file without `evndispLog` object.
This was originally introduced to read the VPM quality flags from the log files (if the pointing monitor data was there or not). This is not necessary anymore, as the full run info and DQM information including the VPM status is not added to the header.
(and it `evndispLog` is not filled anymore with v490.7 into the anasum files to simplify the analysis chain).

Run without Eventdisplay log file

---

pyV2DL3/eventdisplay/fillEVENTS.py

Resolves #213
Using `scipy.stats.circmean` to get the circular mean when getting the average RA.

Using circmean to get circular mean

---

README.md
environment-eventdisplay.yml
utils/v2dl3-eventdisplay-docker/README.md

Update readme to take recent installation (with pip) improvements into account.
Change conda installation to new `astropy-base` (as we don't need all the auxiliary packages).

README updates
